CREATE TABLE "Dim_Date" (
  "date_sk" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "full_date" date UNIQUE NOT NULL,
  "year" int,
  "month" int,
  "day" int,
  "quarter" int,
  "semester" int
);

CREATE TABLE "Dim_Category" (
  "category_sk" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "bk_category" int UNIQUE NOT NULL,
  "category_name" varchar(255),
  "subcategory_name" varchar(255)
);

CREATE TABLE "Dim_Location" (
  "location_sk" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "postal_code" varchar(20),
  "city" varchar(100),
  "address" varchar(255),
  "local_code" varchar(50)
);

CREATE TABLE "Dim_Saison" (
  "saison_sk" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "bk_saison" varchar(100) UNIQUE NOT NULL,
  "saison_name" varchar(100),
  "weather_description" text
);

CREATE TABLE "Dim_Beneficiary" (
  "beneficiary_sk" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "bk_beneficiary" int UNIQUE NOT NULL,
  "first_name" varchar(100),
  "last_name" varchar(100),
  "email" varchar(255),
  "phone" varchar(50)
);

CREATE TABLE "Dim_Provider" (
  "provider_sk" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "bk_provider" int UNIQUE NOT NULL,
  "name_provider" varchar(255),
  "service_type" varchar(100),
  "email" varchar(255),
  "phone" varchar(50),
  "city" varchar(100)
);

CREATE TABLE "Dim_Service" (
  "service_sk" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "bk_service" int UNIQUE NOT NULL,
  "title" varchar(255),
  "description" text
);

CREATE TABLE "Dim_Event" (
  "event_sk" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "bk_event" int UNIQUE NOT NULL,
  "title" varchar(255),
  "type_event" varchar(100),
  "event_date" date
);

CREATE TABLE "Dim_Reservation" (
  "reservation_sk" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "bk_reservation" int UNIQUE NOT NULL,
  "status" varchar(50),
  "reservation_date" date
);

CREATE TABLE "Dim_Evaluation" (
  "evaluation_sk" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "bk_evaluation" int UNIQUE NOT NULL,
  "comment_eval" text
);

CREATE TABLE "Dim_Complaint" (
  "complaint_sk" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "bk_complaint" int UNIQUE NOT NULL,
  "subject" varchar(255),
  "description" text,
  "status" varchar(50)
);

-- CREATE TABLE "Dim_Marketing_Spend" (
--   "marketing_spend_sk" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
--   "bk_marketing_spend" int UNIQUE NOT NULL,
--   "spend_date" date,
--   "season_spend" varchar(100)
-- );

CREATE TABLE "Dim_Competitor" (
  "competitor_sk" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "bk_competitor" varchar(100) UNIQUE NOT NULL,
  "brand_name" varchar(255),
  "brand_description" text,
  "top_features" text
);

CREATE TABLE "Dim_Reviews" (
  "reviews_sk" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "bk_review" varchar(100) UNIQUE NOT NULL,
  "username" varchar(255),
  "title" varchar(255),
  "description" text
);

CREATE TABLE "Fact_Revenues" (
  "reservation_fk" int,
  "service_fk" int,
  "evaluation_fk" int,
  "event_key" int,
  "category_fk" int,
  "location_fk" int,
  "saison_fk" int,
  "reviews_fk" int,
  "beneficiary_fk" int,
  "provider_fk" int,
  "complaint_fk" int,
  "competitor_fk" int,
  "event_date_fk" int,
  "reservation_date_fk" int,
  "visitor_date_fk" int,
  "marketing_spend_date_fk" int,
  "price_services" numeric(10,2),
  "budget_events" numeric(12,2),
  "final_price_reservation" numeric(12,2),
  "marketing_spend" numeric(12,2),
  "new_beneficiaries" int,
  "reservation_visits_count" int,
  "visitor_count" int,
  "rating_evaluation" numeric(3,2),
  "starting_price_competitor" numeric(10,2),
  "rating_stars_competitor" numeric(3,2),
  "rating_quality_price" numeric(3,2),
  "rating_features" numeric(3,2),
  "rating_reviews" numeric(3,2)
);

ALTER TABLE "Fact_Revenues" ADD FOREIGN KEY ("reservation_fk") REFERENCES "Dim_Reservation" ("reservation_sk");

ALTER TABLE "Fact_Revenues" ADD FOREIGN KEY ("service_fk") REFERENCES "Dim_Service" ("service_sk");

ALTER TABLE "Fact_Revenues" ADD FOREIGN KEY ("evaluation_fk") REFERENCES "Dim_Evaluation" ("evaluation_sk");

ALTER TABLE "Fact_Revenues" ADD FOREIGN KEY ("event_key") REFERENCES "Dim_Event" ("event_sk");

-- ALTER TABLE "Fact_Revenues" ADD FOREIGN KEY ("marketing_spend_fk") REFERENCES "Dim_Marketing_Spend" ("marketing_spend_sk");

ALTER TABLE "Fact_Revenues" ADD FOREIGN KEY ("category_fk") REFERENCES "Dim_Category" ("category_sk");

ALTER TABLE "Fact_Revenues" ADD FOREIGN KEY ("location_fk") REFERENCES "Dim_Location" ("location_sk");

ALTER TABLE "Fact_Revenues" ADD FOREIGN KEY ("saison_fk") REFERENCES "Dim_Saison" ("saison_sk");

ALTER TABLE "Fact_Revenues" ADD FOREIGN KEY ("reviews_fk") REFERENCES "Dim_Reviews" ("reviews_sk");

ALTER TABLE "Fact_Revenues" ADD FOREIGN KEY ("beneficiary_fk") REFERENCES "Dim_Beneficiary" ("beneficiary_sk");

ALTER TABLE "Fact_Revenues" ADD FOREIGN KEY ("provider_fk") REFERENCES "Dim_Provider" ("provider_sk");

ALTER TABLE "Fact_Revenues" ADD FOREIGN KEY ("complaint_fk") REFERENCES "Dim_Complaint" ("complaint_sk");

ALTER TABLE "Fact_Revenues" ADD FOREIGN KEY ("competitor_fk") REFERENCES "Dim_Competitor" ("competitor_sk");

ALTER TABLE "Fact_Revenues" ADD FOREIGN KEY ("event_date_fk") REFERENCES "Dim_Date" ("date_sk");

ALTER TABLE "Fact_Revenues" ADD FOREIGN KEY ("reservation_date_fk") REFERENCES "Dim_Date" ("date_sk");

ALTER TABLE "Fact_Revenues" ADD FOREIGN KEY ("visitor_date_fk") REFERENCES "Dim_Date" ("date_sk");

ALTER TABLE "Fact_Revenues" ADD FOREIGN KEY ("marketing_spend_date_fk") REFERENCES "Dim_Date" ("date_sk");
